#!/bin/bash
echo "Upgrading Raspberry system files, this may take a while."
# update repository links
sudo apt-get update
# get latest version of all files
sudo apt-get upgrade

echo "Installing dependencies, this may take a while."
# install dependencies
sudo apt-get install git-core couchdb nodejs python3 python3-pip couchapp
# install even more dependencies
sudo pip3 install requests
# install final dependency
git clone git://git.drogon.net/wiringPi

echo "Building wiringPi: an implementation of most of the Arduino Wiring
	functions for the Raspberry Pi"
cd wiringPi
./build
cd ..

echo "Clone and install SwitchIt"
# install actual program
git clone git://github.com/Sijmen/switchit.git
cd switchit/lights
make rebuild
sudo chown root *.o && sudo chmod =x *.o && sudo chmod +s *.o
cd ..

# start automatic configuration.
python3 setup/server.py
